# -*- coding: utf-8 -*-
"""load_model pombEye-V1

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1bGhAslikqM5MJiBaASiUyRwLtX3fE29H
"""

from keras.preprocessing import image
from keras.models import Sequential , Model
from keras import backend as K
from keras.applications.vgg16 import VGG16
from keras.applications.vgg16 import preprocess_input
import numpy as np
from keras import models
from keras import layers
from keras import optimizers
from keras.models import load_model
import os
from numpy import ndarray
import cv2
import tensorflow as tf
import sys


tf.logging.set_verbosity(tf.logging.ERROR)

model = load_model(os.path.join(os.path.dirname(__file__), 'pombEye_V1.h5'))

model.compile(loss='categorical_crossentropy',
              optimizer=optimizers.RMSprop(lr=1e-4),
              metrics=['acc'])



categories = {'Cytosol': 0,
 'Cytosol and Nucleus': 1,
 'Endoplasmic reticulum': 2,
 'Golgi': 3,
 'Microtubules': 4,
 'Mitochondrion': 5,
 'Nucleus': 6,
 'Periphery': 7,
 'Vacuole': 8}

print("Type 'exit' to quit pombEye")


while True:
    filename = input("Enter file path: ")
    filename = str(filename)
    filename = filename.rstrip()
    if filename == 'exit':
        break
    try:
        assert os.path.exists(filename), "File not found at, "+str(filename)
        img = cv2.imread(filename,0)
        cv2.imwrite('temp.jpg',img)
        test_image = image.load_img(os.path.join(os.path.dirname(__file__),'temp.jpg'), target_size = (300, 300))
        test_image = image.img_to_array(test_image)
        test_image = np.expand_dims(test_image, axis = 0)
        test_image = test_image.astype("float") / 255.0
        result = model.predict(test_image)
        print("\n\n")
        print("Input converted to grayscale and saved as temp.jpg in the working directory")
        print("\n")
        print("Predicted localisation")
        print("Prediction", " : ", "Confidence score (Max value = 100)")
        for classes, number in categories.items():
            if number == result.argmax():
                print(classes, " : ", round(np.amax(result)*100,2),"\n\n")
        for classes, number in categories.items():
            print(classes, " " , round(result.item(number)*100,2))
        print("\n\n")
        continue
    except:
        print("Not a valid input")
        continue
